server:
  port: 8089
spring:
  application:
    name: spring-security-auth
  datasource:
    # 使用Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3307/spring_security_oauth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 50
      max-wait: 60000
      min-idle: 5
  redis:
    host: localhost
    port: 6379
    password: 1
jwt:
  key:
    alias: weihong
    password: lanweihong
    storepass: lanweihong
    path: jwt.jks
debug: true